sylius_admin_report:
    resource: |
        alias: sylius.report
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['delete']
        redirect: update
        grid: sylius_admin_report
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_shipping_destinations
                templates:
                    form: SyliusReportBundle::_form.html.twig
            index:
                icon: flag
    type: sylius.resource